"use strict";

const {
  consolidateRequirements,
  generateManualCases,
  generateCasesFromUrlAnalysis,
  generateManagerReport
} = require("../services/orchestrator/pipeline");

describe("orchestrator evidence-driven values", () => {
  it("builds requirements, modules, assumptions, and risks from run evidence", () => {
    const requirements = consolidateRequirements({
      ottUrl: "https://cover.example",
      notes: "Claims must preserve the entered policy number",
      _webAnalysisInsights: {
        websiteType: "Banking/Finance Portal",
        websiteTypeConfidence: 0.92,
        subDomain: "Insurance",
        subDomainConfidence: 0.84,
        subDomainSource: "rules"
      },
      _domainClassification: {
        source: "rules",
        testPriorities: ["Premium Quote Calculator"],
        criticalFlows: ["Claim Registration"]
      },
      _suggestedRequirements: [
        { id: "REQ-7", description: "Policy search returns matching policies" }
      ],
      _suggestedTestAreas: ["Policy Search"],
      _autoGeneratedTestCases: [{ module: "Quote", scenario: "Calculate premium" }],
      _userFlows: [{ name: "Claim Registration", priority: "Critical" }],
      _observations: [{ type: "warning", message: "Captcha detected on claim submission" }],
      _brdDocument: {
        functionalRequirements: [
          { id: "BRD-2", description: "Claim status is visible", testable: true }
        ],
        projectScope: {
          assumptions: ["A test policy is available"],
          constraints: ["Testing is limited to the public claim journey"]
        },
        riskAssessment: [
          {
            id: "RISK-1",
            description: "Claim submission requires OTP",
            mitigation: "Use a test OTP provider"
          }
        ]
      }
    });

    expect(requirements.metadata.valueMode).toBe("analyzer-and-user-evidence");
    expect(requirements.metadata.classificationSource).toBe("rules");
    expect(requirements.requirementStatements).toEqual(expect.arrayContaining([
      "Premium Quote Calculator must work correctly for the Insurance journey.",
      "Claim Registration must complete end-to-end without blocking errors.",
      "REQ-7: Policy search returns matching policies",
      "BRD-2: Claim status is visible",
      "Claims must preserve the entered policy number"
    ]));
    expect(requirements.modules).toEqual(["Policy Search", "Quote", "Claim Registration"]);
    expect(requirements.channelContext.audience).toBe("Insurance users");
    expect(requirements.channelContext.releaseIntent).toContain("1 discovered critical");
    expect(requirements.assumptions).toContain("A test policy is available");
    expect(requirements.risks).toEqual(expect.arrayContaining([
      "RISK-1: Claim submission requires OTP Mitigation: Use a test OTP provider",
      "Testing is limited to the public claim journey",
      "Captcha detected on claim submission"
    ]));
  });

  it("labels deterministic profile values as fallback when evidence is absent", () => {
    const requirements = consolidateRequirements({
      ottUrl: "https://unknown.example"
    });

    expect(requirements.metadata.valueMode).toBe("profile-template-fallback");
    expect(requirements.metadata.evidence.level).toBe("none");
    expect(requirements.requirementStatements.length).toBeGreaterThan(0);
    expect(requirements.risks).toEqual([]);
  });

  it("derives values from analyzer structure when a crawl returns almost nothing", () => {
    const requirements = consolidateRequirements({
      ottUrl: "https://www.zepto.com/",
      _webAnalysisInsights: {
        websiteType: "Website",
        websiteTypeConfidence: 0,
        pagesCrawled: 1,
        topNavLabels: [],
        userJourneys: [],
        criticalPaths: [],
        keyFunctionalities: [],
        formAnalysis: []
      },
      _allElements: {},
      _suggestedRequirements: [],
      _suggestedTestAreas: [
        { area: "Navigation", priority: "High", tests: ["Menu items", "Footer links"] }
      ],
      _autoGeneratedTestCases: [{ module: "Content Display" }],
      _userFlows: [],
      _observations: [
        { type: "summary", stats: { elementsFound: 0, formsFound: 0, userFlowsDetected: 0, pagesCrawled: 1 } }
      ],
      _brdDocument: {
        projectScope: { inScope: ["Forms: Functional verification and testing"] },
        testStrategy: { testTypes: [{ type: "Responsiveness", priority: "High" }] },
        functionalRequirements: [],
        nonFunctionalRequirements: [
          { id: "NFR-004", description: "All pages should be served over HTTPS" }
        ]
      }
    });

    expect(requirements.metadata.hasUrlAnalysis).toBe(true);
    expect(requirements.metadata.valueMode).toBe("analyzer-structure-evidence");
    expect(requirements.metadata.evidence).toMatchObject({ level: "analyzer-thin", pagesCrawled: 1 });
    expect(requirements.requirementStatements).toEqual(expect.arrayContaining([
      "Navigation must cover Menu items, Footer links.",
      "Responsiveness testing must work correctly on www.zepto.com.",
      "Forms: Functional verification and testing must work correctly on www.zepto.com.",
      "NFR-004: All pages should be served over HTTPS"
    ]));
    // A generic OTT channel profile must not describe a grocery site.
    expect(requirements.userJourneys).not.toContain("Attempt playback and controls");
    expect(requirements.userJourneys).toEqual(expect.arrayContaining(["Navigation", "Content Display"]));
    expect(requirements.risks[0]).toContain("Crawl evidence for www.zepto.com is thin");

    const manualCases = generateManualCases(requirements);
    expect(manualCases.testCases.length).toBeGreaterThan(0);
    expect(manualCases.testCases.some((testCase) => /playback/i.test(testCase.scenario))).toBe(false);
    expect(manualCases.testCases[0].traceability).toContain("analyzer-structure-evidence");
  });

  it("uses analyzer-generated cases without adding generic BRD or feature cases", () => {
    const report = generateCasesFromUrlAnalysis(
      {
        majorFunctionalCases: [{
          id: "TC-MAJ-001",
          module: "Claim Registration",
          scenario: "Submit a claim",
          title: "Insurance: Submit a claim",
          priority: "Critical",
          steps: ["Open claims", "Submit claim"],
          expectedResult: "Claim reference is displayed",
          traceability: "majorFunctionalCases:subDomainCriticalFlow"
        }],
        features: [{ name: "Generic navigation", type: "core" }],
        brdDocument: {
          functionalRequirements: [{
            id: "BRD-1",
            feature: "Generic form",
            description: "A form is displayed",
            testable: true
          }]
        }
      },
      {
        metadata: {
          profile: "Insurance",
          websiteType: "Banking/Finance Portal",
          subDomain: "Insurance"
        }
      }
    );

    expect(report.metadata.caseSource).toBe("majorFunctionalCases");
    expect(report.testCases).toHaveLength(1);
    expect(report.testCases[0].module).toBe("Claim Registration");
  });

  it("manager report counts executed flows and names waitFor timeouts", () => {
    const report = generateManagerReport(
      { metadata: { profile: "Generic", profileKey: "default", ottUrl: "https://shop.example" } },
      { testCases: new Array(19).fill(0).map((_, i) => ({ id: `TC-${i}`, module: "Other" })) },
      {},
      {
        totals: { total: 5, passed: 0, failed: 5, passRate: "0%" },
        tests: [
          { id: "FLOW-001", title: "Site Navigation", status: "failed", error: "locator.waitFor: Timeout 8000ms exceeded. Call log: - wait" }
        ]
      }
    );

    expect(report.executiveSummary.executed).toBe(1);
    expect(report.executiveSummary.totalTestCases).toBe(1);
    expect(report.analysis.rootCauses[0]).toMatch(/timed out waiting for visible elements/);
  });
});
