"use strict";

const { generateCasesFromUrlAnalysis } = require("../services/orchestrator/pipeline");
const {
  generateMajorFunctionalCases,
} = require("../packages/analyzer/lib/generate/majorFunctionalCases");
const { buildSiteContext } = require("../services/orchestrator/siteContext");

const requirements = { metadata: { profile: "Insurance" } };

describe("case generation stays specific to the analyzed site", () => {
  it("keeps the evidence-backed cases instead of only the domain catalog cases", () => {
    const report = generateCasesFromUrlAnalysis(
      {
        majorFunctionalCases: [
          {
            id: "TC-MAJ-001",
            module: "Claim Intimation",
            scenario: "Verify Claim Intimation functionality",
            steps: ["Navigate to the Claim Intimation entry point"],
            expectedResult: "Works",
          },
        ],
        // The merged analyzer set: catalog case plus a form-derived one.
        autoGeneratedTestCases: [
          {
            id: "TC-MAJ-001",
            module: "Claim Intimation",
            scenario: "Verify Claim Intimation functionality",
            steps: ["Navigate to the Claim Intimation entry point"],
            expectedResult: "Works",
          },
          {
            id: "TC-FORM-002",
            module: "Forms",
            scenario: "Claim Form - Valid Data Submission",
            steps: [
              { stepNumber: 1, action: "Input", description: "Enter valid data in Policy Number field" },
              { stepNumber: 2, action: "Click", description: "Click Submit Claim button" },
            ],
            expectedResults: ["Form submits without errors", "Success message is shown"],
            preconditions: ["Navigate to page containing claim form"],
            testData: [{ field: "Policy Number", value: "POL-1", validation: "Required" }],
          },
        ],
      },
      requirements
    );

    expect(report.metadata.caseSource).toBe("autoGeneratedTestCases");
    expect(report.testCases).toHaveLength(2);

    const formCase = report.testCases.find((tc) => tc.module === "Forms");
    expect(formCase.scenario).toBe("Claim Form - Valid Data Submission");
    // Object steps must be flattened to strings for reports and script builders.
    expect(formCase.steps).toEqual([
      "Input: Enter valid data in Policy Number field",
      "Click: Click Submit Claim button",
    ]);
    expect(formCase.expectedResult).toBe(
      "Form submits without errors; Success message is shown"
    );
    expect(formCase.preconditions).toBe("Navigate to page containing claim form");
    expect(formCase.testData).toBe("Policy Number=POL-1");
  });

  it("falls back to the domain cases when no merged set is present", () => {
    const report = generateCasesFromUrlAnalysis(
      {
        majorFunctionalCases: [
          { id: "TC-MAJ-001", module: "Claim Intimation", scenario: "Submit a claim" },
        ],
      },
      requirements
    );

    expect(report.metadata.caseSource).toBe("majorFunctionalCases");
    expect(report.testCases).toHaveLength(1);
  });

  it("writes steps that name real navigation labels, paths and form fields", () => {
    const cases = generateMajorFunctionalCases({
      websiteType: {
        type: "BANKING_FINANCE",
        typeName: "Banking/Finance Portal",
        testPriorities: ["Claim Intimation", "Branch Locator"],
        criticalFlows: [],
      },
      subDomain: null,
      userFlows: [],
      elements: [],
      pageStructure: { title: "CoverPlus Insurance" },
      crawledPages: [
        { path: "/", title: "CoverPlus Insurance", navLabels: ["Claim Intimation", "About"] },
        { path: "/branches", title: "Find a Branch", navLabels: [] },
      ],
      forms: [
        {
          purpose: "claim intimation",
          fields: [{ label: "Policy Number" }, { label: "Incident Date" }],
          submitButton: { text: "Submit Claim" },
        },
      ],
    });

    const claim = cases.find((tc) => tc.module === "Claim Intimation");
    expect(claim.steps[0]).toBe(
      'From the homepage, open "Claim Intimation" in the main navigation'
    );
    expect(claim.steps[2]).toBe(
      'Complete the claim intimation form (Policy Number, Incident Date) and submit using "Submit Claim"'
    );
    expect(claim.preconditions).toBe('Homepage "CoverPlus Insurance" loaded');
    expect(claim.evidenceSource).toBe("nav");

    // No nav label for this one, but a crawled page matches.
    const branch = cases.find((tc) => tc.module === "Branch Locator");
    expect(branch.steps[0]).toBe('Navigate to /branches ("Find a Branch")');
    expect(branch.evidenceSource).toBe("page");
  });

  it("still produces a case when the crawl yields no matching evidence", () => {
    const cases = generateMajorFunctionalCases({
      websiteType: { typeName: "Website", testPriorities: ["Responsiveness"], criticalFlows: [] },
      userFlows: [],
      elements: [],
      crawledPages: [{ path: "/", title: "Home" }],
    });

    const responsive = cases.find((tc) => tc.module === "Responsiveness");
    expect(responsive.steps[0]).toBe("Navigate to the Responsiveness entry point");
    expect(responsive.evidenceSource).toBe("catalog");
  });
});

describe("LLM site context", () => {
  const analysis = {
    metadata: { url: "https://cover.example" },
    pageStructure: { title: "CoverPlus", headings: [{ level: 1, text: "Insurance made simple" }] },
    domainClassification: { domain: "Banking/Finance Portal", subDomain: "Insurance" },
    crawledPages: [{ path: "/", title: "Home", navLabels: ["Claims", "Renew"] }],
    forms: [{ purpose: "claim", fields: [{ label: "Policy Number" }] }],
    allElements: { NAVIGATION: [{}, {}], FORMS: [{}] },
    userFlows: [{ name: "Claim Registration" }],
    observations: [{ message: "Detected 1 user flow" }],
  };

  it("carries the crawl facts an agent needs to write specific cases", () => {
    const context = buildSiteContext(analysis);

    expect(context.siteTitle).toBe("CoverPlus");
    expect(context.subDomain).toBe("Insurance");
    expect(context.pages[0].navLabels).toEqual(["Claims", "Renew"]);
    expect(context.forms[0]).toEqual({ purpose: "claim", fields: ["Policy Number"] });
    expect(context.headings).toEqual(["H1: Insurance made simple"]);
    expect(context.elementCategories).toEqual({ NAVIGATION: 2, FORMS: 1 });
  });

  it("returns null when there is nothing trustworthy to describe", () => {
    expect(buildSiteContext(null)).toBeNull();
    expect(buildSiteContext({ analysisFailed: true, crawledPages: [{ path: "/" }] })).toBeNull();
    expect(buildSiteContext({ insufficientEvidence: true })).toBeNull();
    // Reached the site but learned nothing worth sending.
    expect(buildSiteContext({ metadata: { url: "https://x.example" } })).toBeNull();
  });
});
