const { loadEcommerceConfig } = require("../shared/ecommerce");
const { sanitizeTestTitle } = require("../shared/text");
const { normalizeTestCases } = require("./testCasesSpec");

const ECOMMERCE_HELPER_BLOCK = [
  "/**",
  " * Try multiple selectors until one works",
  " */",
  "async function findElement(page, selectors, options = {}) {",
  "  const { timeout = 5000, action = 'find' } = options;",
  "  for (const sel of selectors || []) {",
  "    try {",
  "      const loc = page.locator(sel).first();",
  "      if (await loc.isVisible({ timeout: Math.min(timeout, 3000) })) {",
  "        if (action === 'click') await loc.click();",
  "        if (action === 'fill' && options.value) {",
  "          await loc.click();",
  "          await loc.fill(options.value);",
  "        }",
  "        return loc;",
  "      }",
  "    } catch { /* try next selector */ }",
  "  }",
  "  return null;",
  "}",
  "",
  "async function expectVisible(page, selectors, timeout = 5000) {",
  "  const el = await findElement(page, selectors, { timeout });",
  "  if (!el) throw new Error(`Element not found with selectors: ${selectors.slice(0,2).join(', ')}`);",
  "  await expect(el).toBeVisible();",
  "  return el;",
  "}",
  "",
  "async function searchAndNavigate(page, searchTerm) {",
  "  const searchInput = await findElement(page, SELECTORS.search.input, { action: 'fill', value: searchTerm });",
  "  if (!searchInput) throw new Error('Search input not found');",
  "  const submitBtn = await findElement(page, SELECTORS.search.submit, { action: 'click', timeout: 3000 });",
  "  if (!submitBtn) await page.keyboard.press('Enter');",
  "  await page.waitForLoadState('domcontentloaded');",
  "  await page.waitForTimeout(2000);",
  "}",
  "",
  "async function clickProduct(page, index = 0) {",
  "  await page.waitForTimeout(1000);",
  "  const products = page.locator(SELECTORS.results.productCard.join(', '));",
  "  const count = await products.count();",
  "  if (count === 0) throw new Error('No products found in results');",
  "  await products.nth(Math.min(index, count - 1)).click();",
  "  await page.waitForLoadState('domcontentloaded');",
  "  await page.waitForTimeout(2000);",
  "}",
  "",
  "async function addToCart(page) {",
  "  const btn = await findElement(page, SELECTORS.productPage.addToCart, { action: 'click' });",
  "  if (!btn) throw new Error('Add to Cart button not found');",
  "  await page.waitForTimeout(2000);",
  "}",
  "",
  "async function openCart(page) {",
  "  const cartIcon = await findElement(page, SELECTORS.cart.icon, { action: 'click' });",
  "  if (!cartIcon) {",
  "    const cartUrl = BASE_URL.replace(/\\/$/, '') + '/viewcart';",
  "    await page.goto(cartUrl, { waitUntil: 'domcontentloaded' });",
  "  }",
  "  await page.waitForLoadState('domcontentloaded');",
  "  await page.waitForTimeout(2000);",
  "}"
].join("\n");

function buildEcommerceTestBody(testCase) {
  const action = String(testCase.action || "").toLowerCase();
  const searchTerm = testCase.testData || testCase.searchTerm || "iPhone 15";
  const lines = [
    "    await page.goto(BASE_URL, { waitUntil: 'domcontentloaded' });",
    "    await page.waitForTimeout(2000);"
  ];

  if (action.includes("search") || action.includes("enter")) {
    lines.push(`    await searchAndNavigate(page, ${JSON.stringify(searchTerm)});`);
  }
  if (action.includes("click_product") || action.includes("select")) {
    lines.push("    await clickProduct(page);");
  }
  if (action.includes("add") && action.includes("cart")) {
    lines.push("    await addToCart(page);");
  }
  if (action.includes("open_cart") || action.includes("view_cart")) {
    lines.push("    await openCart(page);");
  }
  if (action.includes("verify")) {
    const expected = testCase.expectedResult || "visible";
    lines.push(`    // Verify: ${String(expected).slice(0, 50)}`);
    lines.push("    await page.waitForTimeout(1000);");
  }

  return lines;
}

function buildGenericEcommerceFlow() {
  return [
    "test('Complete E-Commerce Flow', async ({ page }) => {",
    "  await page.goto(BASE_URL, { waitUntil: 'domcontentloaded' });",
    "  await page.waitForTimeout(2000);",
    "  await searchAndNavigate(page, 'iPhone 15');",
    "  await clickProduct(page);",
    "  await addToCart(page);",
    "  await openCart(page);",
    "  await expectVisible(page, SELECTORS.cart.itemTitle);",
    "});"
  ];
}

/**
 * Build domain-aware e-commerce Playwright script from test cases.
 */
function buildEcommerceSpec(url, testCases, options = {}) {
  const { siteName, domain, config } = loadEcommerceConfig(url);
  const cases = normalizeTestCases(testCases);
  const lines = [
    "/**",
    ` * Domain-Aware E-Commerce Test: ${siteName}`,
    ` * URL: ${url}`,
    " * Generated by Zero QA - Wisecraft AI",
    " */",
    "import { test, expect } from '@playwright/test';",
    "",
    `const BASE_URL = ${JSON.stringify(url)};`,
    `const DOMAIN = ${JSON.stringify(domain)};`,
    "",
    "// Domain-specific selectors",
    `const SELECTORS = ${JSON.stringify(config, null, 2)};`,
    "",
    ECOMMERCE_HELPER_BLOCK,
    ""
  ];

  if (cases.length > 0) {
    lines.push(`test.describe('${siteName} E-Commerce Tests', () => {`, "");

    cases.forEach((testCase, index) => {
      const title = sanitizeTestTitle(testCase.title || testCase.scenario, `Test Case ${index + 1}`);
      lines.push(`  test(${JSON.stringify(title)}, async ({ page }) => {`);
      lines.push(...buildEcommerceTestBody(testCase));
      lines.push("  });", "");
    });

    lines.push("});");
  } else {
    lines.push(...buildGenericEcommerceFlow());
  }

  return lines.join("\n");
}

module.exports = {
  buildEcommerceSpec,
  buildEcommerceTestBody
};
