function formatForBAAgent(analysisResult) {
  const typeName = analysisResult.websiteType?.typeName;
  const subName = analysisResult.subDomain?.name;
  const classifiedAs = [typeName, subName].filter(Boolean).join(" / ");
  const asClause = classifiedAs ? ` as ${classifiedAs}` : "";

  const thinNote = analysisResult.thinCrawl
    ? " The page UI was not readable; test areas come from the classified site type."
    : "";

  return {
    summary: `Analyzed ${analysisResult.url}${asClause}. Found ${analysisResult.elements?.length || 0} elements, ${analysisResult.forms?.length || 0} forms, ${analysisResult.userFlows?.length || 0} user flows.${thinNote}`,
    
    websiteInfo: {
      type: analysisResult.websiteType?.typeName || 'Website',
      typeConfidence: analysisResult.websiteType?.confidence || 0,
      title: analysisResult.pageStructure?.title,
      url: analysisResult.url
    },
    
    keyFunctionalities: analysisResult.brd?.functionalRequirements?.slice(0, 10).map(req => ({
      name: req.feature,
      priority: req.priority,
      testable: req.testable
    })) || [],
    
    userJourneys: analysisResult.userFlows?.map(f => f.name) || [],
    
    criticalPaths: analysisResult.userFlows?.filter(f => f.priority === 'Critical').map(f => f.name) || [],
    
    riskAreas: analysisResult.brd?.riskAssessment?.map(r => r.description) || [],
    
    formAnalysis: analysisResult.forms?.map(f => ({
      purpose: f.purpose,
      fieldCount: f.fieldCount,
      hasValidation: f.fields.some(field => field.required)
    })) || [],
    
    navigationStructure: {
      menuItems: analysisResult.elements?.filter(e => e.category === 'NAVIGATION').length || 0,
      pageHierarchy: analysisResult.pageStructure?.headings?.map(h => `H${h.level}: ${h.text}`).slice(0, 15) || []
    },
    
    testingRecommendations: [
      ...(analysisResult.thinCrawl ? ['The landing page rendered little UI — re-run headed, or complete the site location/login gate, then re-analyse'] : []),
      ...(analysisResult.antiBot ? ['Use headed browser mode due to anti-bot protection'] : []),
      ...(analysisResult.dynamicContent ? ['Use data-testid selectors for stable automation'] : []),
      ...(analysisResult.websiteType?.testPriorities?.slice(0, 3).map(p => `Prioritize: ${p} testing`) || [])
    ],
    
    autoGeneratedTestCases: analysisResult.testCases || [],
    
    brdDocument: analysisResult.brd,
    
    observations: analysisResult.observations,
    warnings: analysisResult.warnings
  };
}

module.exports = { formatForBAAgent };
