/**
 * Generate Selenium Java test scripts (language: Java, not JavaScript).
 * Used for automation scripts stored in SQL and export to a Java project (e.g. TVNZ).
 */

function escapeJava(s) {
  if (s == null) return "";
  return String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}

/**
 * Build one Selenium Java test method for a TC.
 * @param {Object} tc - { id, module, scenario, expectedResult, title }
 * @param {Object} locatorsByKey - { playCta: [{ selectorValue, selectorType }], ... }
 * @param {string} baseUrl
 */
function buildSeleniumJavaTest(tc, locatorsByKey, baseUrl) {
  const id = tc.id || "TC-001";
  const title = (tc.title || tc.scenario || id).replace(/"/g, "'");
  const scenario = (tc.scenario || "").replace(/"/g, "'");
  const expected = (tc.expectedResult || "").replace(/"/g, "'");
  const url = baseUrl || "https://example.com";

  const lines = [
    "import org.openqa.selenium.By;",
    "import org.openqa.selenium.WebDriver;",
    "import org.openqa.selenium.WebElement;",
    "import org.openqa.selenium.support.ui.ExpectedConditions;",
    "import org.openqa.selenium.support.ui.WebDriverWait;",
    "import java.time.Duration;",
    "",
    "public class " + id.replace(/[^a-zA-Z0-9]/g, "_") + " {",
    "",
    "    public static void run(WebDriver driver, String baseUrl) {",
    "        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));",
    "        driver.get(baseUrl != null ? baseUrl : \"" + escapeJava(url) + "\");",
    "        wait.until(ExpectedConditions.visibilityOfElementLocated(By.tagName(\"body\")));",
    ""
  ];

  const selectors = locatorsByKey || {};
  const playSelectors = (selectors.playCta || []).map((s) => s.selectorValue || s).filter(Boolean);
  const cardSelectors = (selectors.contentCard || []).map((s) => s.selectorValue || s).filter(Boolean);

  if (playSelectors.length) {
    lines.push("        // Play CTA");
    lines.push("        WebElement play = null;");
    for (const sel of playSelectors.slice(0, 3)) {
      const by = sel.startsWith("//") ? `By.xpath(\"${escapeJava(sel)}\")` : `By.cssSelector(\"${escapeJava(sel)}\")`;
      lines.push("        try { play = wait.until(ExpectedConditions.elementToBeClickable(" + by + ")); } catch (Exception e) {}");
      lines.push("        if (play != null) { play.click(); return; }");
    }
    lines.push("");
  }

  if (cardSelectors.length) {
    lines.push("        // Content card");
    const sel = cardSelectors[0];
    const by = sel.startsWith("//") ? `By.xpath(\"${escapeJava(sel)}\")` : `By.cssSelector(\"${escapeJava(sel)}\")`;
    lines.push("        WebElement card = wait.until(ExpectedConditions.elementToBeClickable(" + by + "));");
    lines.push("        if (card != null) card.click();");
    lines.push("");
  }

  lines.push("        // Assertion: " + escapeJava(expected.slice(0, 60)));
  lines.push("        wait.until(ExpectedConditions.visibilityOfElementLocated(By.tagName(\"body\")));");
  lines.push("    }");
  lines.push("}");

  return lines.join("\n");
}

/**
 * Build a full Java test class for a project (multiple TCs).
 */
function buildSeleniumJavaClass(projectName, testCases, locatorsByKey, baseUrl) {
  const className = (projectName || "OTT").replace(/[^a-zA-Z0-9]/g, "") + "Test";
  const lines = [
    "import org.openqa.selenium.By;",
    "import org.openqa.selenium.WebDriver;",
    "import org.openqa.selenium.WebElement;",
    "import org.openqa.selenium.chrome.ChromeDriver;",
    "import org.openqa.selenium.support.ui.ExpectedConditions;",
    "import org.openqa.selenium.support.ui.WebDriverWait;",
    "import java.time.Duration;",
    "",
    "/** Generated by ZER0 - Automation language: Java (Selenium) */",
    "public class " + className + " {",
    "",
    "    private static final String BASE_URL = \"" + escapeJava(baseUrl || "") + "\";",
    "",
    "    public static void main(String[] args) {",
    "        WebDriver driver = new ChromeDriver();",
    "        try {",
    "            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(15));",
    "            driver.get(BASE_URL);",
    "            wait.until(ExpectedConditions.visibilityOfElementLocated(By.tagName(\"body\")));",
    "            // Add test method calls per TC",
    "        } finally {",
    "            driver.quit();",
    "        }",
    "    }",
    "}"
  ];
  return lines.join("\n");
}

/**
 * Build a domain-aware e-commerce Java Selenium test class.
 */
function buildEcommerceSelenium(url, testCases, options = {}) {
  const { detectDomain, domainSelectors } = require("@zero/locators/ecommerceSelectors");
  const domain = detectDomain(url);
  const config = domainSelectors[domain] || domainSelectors.generic;
  const siteName = config.name || domain;
  const className = (siteName + "EcommerceTest").replace(/[^a-zA-Z0-9]/g, "");

  const lines = [
    "/**",
    ` * Domain-Aware E-Commerce Test: ${siteName}`,
    ` * URL: ${url}`,
    " * Generated by Zero QA - Wisecraft AI",
    " */",
    "import org.openqa.selenium.By;",
    "import org.openqa.selenium.WebDriver;",
    "import org.openqa.selenium.WebElement;",
    "import org.openqa.selenium.Keys;",
    "import org.openqa.selenium.chrome.ChromeDriver;",
    "import org.openqa.selenium.chrome.ChromeOptions;",
    "import org.openqa.selenium.support.ui.ExpectedConditions;",
    "import org.openqa.selenium.support.ui.WebDriverWait;",
    "import java.time.Duration;",
    "import java.util.List;",
    "",
    "public class " + className + " {",
    "",
    `    private static final String BASE_URL = "${escapeJava(url)}";`,
    `    private static final String DOMAIN = "${domain}";`,
    "",
    "    // Domain-specific selectors for " + siteName,
    generateSelectorConstants(config),
    "",
    "    private WebDriver driver;",
    "    private WebDriverWait wait;",
    "",
    "    public void setup() {",
    "        ChromeOptions options = new ChromeOptions();",
    "        options.addArguments(\"--start-maximized\");",
    "        driver = new ChromeDriver(options);",
    "        wait = new WebDriverWait(driver, Duration.ofSeconds(15));",
    "    }",
    "",
    "    public void teardown() {",
    "        if (driver != null) driver.quit();",
    "    }",
    "",
    "    private WebElement findElement(String[] selectors) {",
    "        for (String sel : selectors) {",
    "            try {",
    "                By by = sel.startsWith(\"//\") ? By.xpath(sel) : By.cssSelector(sel);",
    "                return wait.until(ExpectedConditions.visibilityOfElementLocated(by));",
    "            } catch (Exception e) { /* try next */ }",
    "        }",
    "        return null;",
    "    }",
    "",
    "    private void clickElement(String[] selectors) {",
    "        WebElement el = findElement(selectors);",
    "        if (el != null) el.click();",
    "    }",
    "",
    "    public void searchProduct(String term) {",
    "        WebElement searchInput = findElement(SEARCH_INPUT);",
    "        if (searchInput != null) {",
    "            searchInput.click();",
    "            searchInput.clear();",
    "            searchInput.sendKeys(term);",
    "            ",
    "            // Try submit button first, then Enter key",
    "            WebElement submitBtn = findElement(SEARCH_SUBMIT);",
    "            if (submitBtn != null) {",
    "                submitBtn.click();",
    "            } else {",
    "                searchInput.sendKeys(Keys.ENTER);",
    "            }",
    "        }",
    "        try { Thread.sleep(2000); } catch (Exception e) {}",
    "    }",
    "",
    "    public void clickFirstProduct() {",
    "        WebElement product = findElement(PRODUCT_CARD);",
    "        if (product != null) product.click();",
    "        try { Thread.sleep(2000); } catch (Exception e) {}",
    "    }",
    "",
    "    public void addToCart() {",
    "        clickElement(ADD_TO_CART);",
    "        try { Thread.sleep(2000); } catch (Exception e) {}",
    "    }",
    "",
    "    public void openCart() {",
    "        clickElement(CART_ICON);",
    "        try { Thread.sleep(2000); } catch (Exception e) {}",
    "    }",
    "",
    "    public boolean verifyInCart() {",
    "        return findElement(CART_ITEM_TITLE) != null;",
    "    }",
    "",
    "    public static void main(String[] args) {",
    `        ${className} test = new ${className}();`,
    "        try {",
    "            test.setup();",
    "            test.driver.get(BASE_URL);",
    "            Thread.sleep(2000);",
    "            ",
    "            // Execute e-commerce flow",
    "            test.searchProduct(\"iPhone 15\");",
    "            test.clickFirstProduct();",
    "            test.addToCart();",
    "            test.openCart();",
    "            ",
    "            if (test.verifyInCart()) {",
    "                System.out.println(\"Test PASSED: Item found in cart\");",
    "            } else {",
    "                System.out.println(\"Test FAILED: Item not found in cart\");",
    "            }",
    "        } catch (Exception e) {",
    "            System.err.println(\"Test error: \" + e.getMessage());",
    "        } finally {",
    "            test.teardown();",
    "        }",
    "    }",
    "}"
  ];

  return lines.join("\n");
}

function generateSelectorConstants(config) {
  const lines = [];
  
  const addArray = (name, arr) => {
    if (arr && arr.length) {
      lines.push(`    private static final String[] ${name} = {${arr.slice(0, 5).map(s => '"' + escapeJava(s) + '"').join(', ')}};`);
    }
  };
  
  addArray("SEARCH_INPUT", config.search?.input);
  addArray("SEARCH_SUBMIT", config.search?.submit);
  addArray("PRODUCT_CARD", config.results?.productCard);
  addArray("PRODUCT_TITLE", config.productPage?.title);
  addArray("PRODUCT_PRICE", config.productPage?.price);
  addArray("ADD_TO_CART", config.productPage?.addToCart);
  addArray("CART_ICON", config.cart?.icon);
  addArray("CART_ITEM_TITLE", config.cart?.itemTitle);
  addArray("PLACE_ORDER", config.cart?.placeOrder);
  
  return lines.join("\n");
}

module.exports = {
  buildSeleniumJavaTest,
  buildSeleniumJavaClass,
  buildEcommerceSelenium,
  escapeJava
};
