/**
 * Generate Selenium Java test scripts (language: Java, not JavaScript).
 * Used for automation scripts stored in SQL and export to a Java project (e.g. TVNZ).
 */

function escapeJava(s) {
  if (s == null) return "";
  return String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}

/**
 * Build one Selenium Java test method for a TC.
 * @param {Object} tc - { id, module, scenario, expectedResult, title }
 * @param {Object} locatorsByKey - { playCta: [{ selectorValue, selectorType }], ... }
 * @param {string} baseUrl
 */
function buildSeleniumJavaTest(tc, locatorsByKey, baseUrl) {
  const id = tc.id || "TC-001";
  const title = (tc.title || tc.scenario || id).replace(/"/g, "'");
  const scenario = (tc.scenario || "").replace(/"/g, "'");
  const expected = (tc.expectedResult || "").replace(/"/g, "'");
  const url = baseUrl || "https://example.com";

  const lines = [
    "import org.openqa.selenium.By;",
    "import org.openqa.selenium.WebDriver;",
    "import org.openqa.selenium.WebElement;",
    "import org.openqa.selenium.support.ui.ExpectedConditions;",
    "import org.openqa.selenium.support.ui.WebDriverWait;",
    "import java.time.Duration;",
    "",
    "public class " + id.replace(/[^a-zA-Z0-9]/g, "_") + " {",
    "",
    "    public static void run(WebDriver driver, String baseUrl) {",
    "        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));",
    "        driver.get(baseUrl != null ? baseUrl : \"" + escapeJava(url) + "\");",
    "        wait.until(ExpectedConditions.visibilityOfElementLocated(By.tagName(\"body\")));",
    ""
  ];

  const selectors = locatorsByKey || {};
  const playSelectors = (selectors.playCta || []).map((s) => s.selectorValue || s).filter(Boolean);
  const cardSelectors = (selectors.contentCard || []).map((s) => s.selectorValue || s).filter(Boolean);

  if (playSelectors.length) {
    lines.push("        // Play CTA");
    lines.push("        WebElement play = null;");
    for (const sel of playSelectors.slice(0, 3)) {
      const by = sel.startsWith("//") ? `By.xpath(\"${escapeJava(sel)}\")` : `By.cssSelector(\"${escapeJava(sel)}\")`;
      lines.push("        try { play = wait.until(ExpectedConditions.elementToBeClickable(" + by + ")); } catch (Exception e) {}");
      lines.push("        if (play != null) { play.click(); return; }");
    }
    lines.push("");
  }

  if (cardSelectors.length) {
    lines.push("        // Content card");
    const sel = cardSelectors[0];
    const by = sel.startsWith("//") ? `By.xpath(\"${escapeJava(sel)}\")` : `By.cssSelector(\"${escapeJava(sel)}\")`;
    lines.push("        WebElement card = wait.until(ExpectedConditions.elementToBeClickable(" + by + "));");
    lines.push("        if (card != null) card.click();");
    lines.push("");
  }

  lines.push("        // Assertion: " + escapeJava(expected.slice(0, 60)));
  lines.push("        wait.until(ExpectedConditions.visibilityOfElementLocated(By.tagName(\"body\")));");
  lines.push("    }");
  lines.push("}");

  return lines.join("\n");
}

/**
 * Build a full Java test class for a project (multiple TCs).
 */
function buildSeleniumJavaClass(projectName, testCases, locatorsByKey, baseUrl) {
  const className = (projectName || "OTT").replace(/[^a-zA-Z0-9]/g, "") + "Test";
  const lines = [
    "import org.openqa.selenium.By;",
    "import org.openqa.selenium.WebDriver;",
    "import org.openqa.selenium.WebElement;",
    "import org.openqa.selenium.chrome.ChromeDriver;",
    "import org.openqa.selenium.support.ui.ExpectedConditions;",
    "import org.openqa.selenium.support.ui.WebDriverWait;",
    "import java.time.Duration;",
    "",
    "/** Generated by ZER0 - Automation language: Java (Selenium) */",
    "public class " + className + " {",
    "",
    "    private static final String BASE_URL = \"" + escapeJava(baseUrl || "") + "\";",
    "",
    "    public static void main(String[] args) {",
    "        WebDriver driver = new ChromeDriver();",
    "        try {",
    "            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(15));",
    "            driver.get(BASE_URL);",
    "            wait.until(ExpectedConditions.visibilityOfElementLocated(By.tagName(\"body\")));",
    "            // Add test method calls per TC",
    "        } finally {",
    "            driver.quit();",
    "        }",
    "    }",
    "}"
  ];
  return lines.join("\n");
}

module.exports = {
  buildSeleniumJavaTest,
  buildSeleniumJavaClass,
  escapeJava
};
