/**
 * Page Object Model builder (Java + Selenium).
 *
 * Produces a proper POM: one Page class (locators + actions) and one JUnit
 * test class per run, using ONLY verified selectors (selectorVerifier output).
 * Unverified selectors are still emitted but clearly flagged with a TODO
 * comment so a human reviewer knows to confirm them - never silently
 * presented as equally reliable.
 */

function escapeJava(s) {
  if (s == null) return "";
  return String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}

function toFieldName(key) {
  return String(key || "element").replace(/[^a-zA-Z0-9]/g, "");
}

function toConstantName(key) {
  return toFieldName(key).replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();
}

function byExpression(selector) {
  if (!selector) return null;
  if (selector.startsWith("//")) return `By.xpath("${escapeJava(selector)}")`;
  if (selector.startsWith(":has-text(") || selector.includes(":has-text(") || selector.includes(":text(")) {
    // Not translatable 1:1 to Selenium CSS; fall back to a text-based XPath.
    const m = selector.match(/:has-text\('([^']*)'\)|:has-text\("([^"]*)"\)/);
    const text = m ? (m[1] || m[2]) : "";
    const tag = selector.split(":")[0] || "*";
    return text ? `By.xpath("//${tag || '*'}[contains(text(),\\"${escapeJava(text)}\\")]")` : null;
  }
  return `By.cssSelector("${escapeJava(selector)}")`;
}

/**
 * Build a Page class from verification report: { key: { verified:[{selector}], unverified:[...] } }
 */
function buildPageObjectClass(className, verificationReport, baseUrl) {
  const cls = (className || "Generated").replace(/[^a-zA-Z0-9]/g, "") + "Page";
  const lines = [
    "import org.openqa.selenium.By;",
    "import org.openqa.selenium.WebDriver;",
    "import org.openqa.selenium.WebElement;",
    "import org.openqa.selenium.support.ui.ExpectedConditions;",
    "import org.openqa.selenium.support.ui.WebDriverWait;",
    "import java.time.Duration;",
    "",
    "/**",
    " * Page Object generated by ZER0.",
    ` * Base URL: ${baseUrl || ""}`,
    " * Locators marked VERIFIED were confirmed present/visible on the live page",
    " * during automation generation. Locators marked UNVERIFIED are best-effort",
    " * fallbacks - review them before relying on this test in CI.",
    " */",
    `public class ${cls} {`,
    "",
    "    private final WebDriver driver;",
    "    private final WebDriverWait wait;",
    "",
    `    public ${cls}(WebDriver driver) {`,
    "        this.driver = driver;",
    "        this.wait = new WebDriverWait(driver, Duration.ofSeconds(12));",
    "    }",
    ""
  ];

  const keys = Object.keys(verificationReport || {});
  for (const key of keys) {
    const { verified = [], unverified = [] } = verificationReport[key] || {};
    const constName = toConstantName(key);
    const bys = [
      ...verified.map((v) => ({ expr: byExpression(v.selector), verified: true, raw: v.selector })),
      ...unverified.map((s) => ({ expr: byExpression(s), verified: false, raw: s }))
    ].filter((b) => b.expr);

    if (!bys.length) continue;

    lines.push(`    // ${key}: ${verified.length} verified / ${verified.length + unverified.length} candidate selector(s)`);
    bys.forEach((b, i) => {
      const flag = b.verified ? "VERIFIED" : "UNVERIFIED - TODO: confirm this selector manually";
      lines.push(`    // [${flag}] ${b.raw}`);
      lines.push(`    private static final By ${constName}_${i} = ${b.expr};`);
    });

    lines.push(`    public WebElement get${toFieldName(key)}() {`);
    lines.push(`        By[] candidates = new By[] { ${bys.map((_, i) => `${constName}_${i}`).join(", ")} };`);
    lines.push("        for (By by : candidates) {");
    lines.push("            try { return wait.until(ExpectedConditions.visibilityOfElementLocated(by)); }");
    lines.push("            catch (Exception e) { /* try next candidate */ }");
    lines.push("        }");
    lines.push(`        throw new org.openqa.selenium.NoSuchElementException("No candidate selector matched for '${key}'");`);
    lines.push("    }");
    lines.push("");
    lines.push(`    public void click${toFieldName(key)}() { get${toFieldName(key)}().click(); }`);
    lines.push("");
  }

  lines.push("    public void open(String url) {");
  lines.push("        driver.get(url);");
  lines.push("        wait.until(ExpectedConditions.visibilityOfElementLocated(By.tagName(\"body\")));");
  lines.push("    }");
  lines.push("}");

  return { className: cls, source: lines.join("\n") };
}

/**
 * Build a JUnit test class that drives the Page Object for a list of test cases.
 */
function buildJUnitTestClass(projectName, pageClassName, testCases, baseUrl) {
  const cls = (projectName || "Generated").replace(/[^a-zA-Z0-9]/g, "") + "Test";
  const lines = [
    "import org.openqa.selenium.WebDriver;",
    "import org.openqa.selenium.chrome.ChromeDriver;",
    "import org.junit.jupiter.api.*;",
    "",
    "/** Generated by ZER0 - one @Test per manual test case, using the Page Object above. */",
    `public class ${cls} {`,
    "",
    "    private WebDriver driver;",
    `    private ${pageClassName} page;`,
    `    private static final String BASE_URL = "${escapeJava(baseUrl || "")}";`,
    "",
    "    @BeforeEach",
    "    public void setup() {",
    "        driver = new ChromeDriver();",
    `        page = new ${pageClassName}(driver);`,
    "        page.open(BASE_URL);",
    "    }",
    "",
    "    @AfterEach",
    "    public void teardown() {",
    "        if (driver != null) driver.quit();",
    "    }",
    ""
  ];

  (testCases || []).slice(0, 60).forEach((tc, idx) => {
    const methodName = "test" + (tc.id || `TC_${idx + 1}`).replace(/[^a-zA-Z0-9]/g, "_");
    lines.push("    @Test");
    lines.push(`    @DisplayName("${escapeJava(tc.title || tc.scenario || tc.id || "Test case")}")`);
    lines.push(`    public void ${methodName}() {`);
    lines.push(`        // Scenario: ${escapeJava(tc.scenario || "")}`);
    lines.push(`        // Expected: ${escapeJava((tc.expectedResult || "").slice(0, 140))}`);
    lines.push("        // TODO: call the relevant page.clickXxx()/getXxx() methods for this scenario");
    lines.push("        Assertions.assertNotNull(driver.getTitle());");
    lines.push("    }");
    lines.push("");
  });

  lines.push("}");
  return { className: cls, source: lines.join("\n") };
}

module.exports = {
  buildPageObjectClass,
  buildJUnitTestClass,
  escapeJava
};

