// AUTO-GENERATED by scripts/generate-analyzer-doc.mjs — do not edit by hand.
// Run `npm run analyser-doc` to refresh from the live packages/analyzer tree.

export interface AnalyzerEntry {
  file: string;
  strategy: string;
  loc: number;
  reExportsFrom: string | null;
  exports: string[];
}

export interface AnalyzerModule {
  file: string;
  loc: number;
  exports: string[];
}

export interface AnalyzerFolder {
  folder: string;
  role: string;
  modules: AnalyzerModule[];
}

export interface AnalyzerDoc {
  generatedAt: string;
  pkg: string;
  version: string | null;
  description: string;
  main: string | null;
  fileCount: number;
  loc: number;
  dependencies: string[];
  entries: AnalyzerEntry[];
  modules: AnalyzerFolder[];
  tree: string;
}

export const ANALYZER_DOC: AnalyzerDoc = {
  "generatedAt": "2026-08-30T16:27:34.814Z",
  "pkg": "@zero/analyzer",
  "version": "0.0.0",
  "description": "Optional URL crawl that seeds BA whenever no TC file is uploaded.",
  "main": "index.js",
  "fileCount": 31,
  "loc": 5242,
  "dependencies": [
    "@zero/locators"
  ],
  "entries": [
    {
      "file": "index.js",
      "strategy": "default (re-exports Pro)",
      "loc": 5,
      "reExportsFrom": "./urlAnalyzerPro",
      "exports": []
    },
    {
      "file": "urlAnalyzerPro.js",
      "strategy": "Pro — deep Playwright crawl",
      "loc": 36,
      "reExportsFrom": null,
      "exports": [
        "analyzeUrlPro",
        "formatForBAAgent",
        "detectWebsiteType",
        "detectSubDomain",
        "scoreSubDomains",
        "generateTestCases",
        "generateBRD",
        "WEBSITE_TYPES",
        "ELEMENT_CATEGORIES",
        "SUB_DOMAINS",
        "getSubDomains",
        "hasSubDomains",
        "subDomainNames",
        "resolveSubDomain"
      ]
    },
    {
      "file": "urlAnalyzer.js",
      "strategy": "Light — heuristic crawl",
      "loc": 19,
      "reExportsFrom": null,
      "exports": [
        "analyzeUrl",
        "generateBRD",
        "generateTestCasesFromAnalysis",
        "formatObservationsForBA",
        "ELEMENT_CATEGORIES",
        "ACTION_TYPES"
      ]
    }
  ],
  "modules": [
    {
      "folder": "lib",
      "role": "shared constants + selector helpers",
      "modules": [
        {
          "file": "lib/constants.js",
          "loc": 260,
          "exports": [
            "WEBSITE_TYPES",
            "ELEMENT_CATEGORIES",
            "LIGHT_ELEMENT_CATEGORIES",
            "ACTION_TYPES",
            "CRITICAL_FORM_PURPOSES",
            "ANTI_BOT_INDICATORS"
          ]
        },
        {
          "file": "lib/selectors.js",
          "loc": 107,
          "exports": [
            "generateSmartSelector",
            "generateBestSelector"
          ]
        }
      ]
    },
    {
      "folder": "lib/classify",
      "role": "website-type detection",
      "modules": [
        {
          "file": "lib/classify/domainTaxonomy.js",
          "loc": 635,
          "exports": [
            "SUB_DOMAINS",
            "getSubDomains",
            "hasSubDomains",
            "subDomainNames",
            "resolveSubDomain"
          ]
        },
        {
          "file": "lib/classify/indicatorMatch.js",
          "loc": 97,
          "exports": [
            "scoreIndicators",
            "matchesIndicator",
            "matchesUrlPattern",
            "indicatorWeight",
            "indicatorPattern",
            "MULTI_WORD_WEIGHT",
            "SINGLE_WORD_WEIGHT"
          ]
        },
        {
          "file": "lib/classify/subDomain.js",
          "loc": 137,
          "exports": [
            "detectSubDomain",
            "scoreSubDomains"
          ]
        },
        {
          "file": "lib/classify/websiteType.js",
          "loc": 125,
          "exports": [
            "detectWebsiteType"
          ]
        }
      ]
    },
    {
      "folder": "lib/crawl",
      "role": "Playwright DOM readers (elements · forms · structure · signals)",
      "modules": [
        {
          "file": "lib/crawl/elements.js",
          "loc": 144,
          "exports": [
            "analyzeElements",
            "analyzeElementLight"
          ]
        },
        {
          "file": "lib/crawl/forms.js",
          "loc": 168,
          "exports": [
            "analyzeFormsDeep"
          ]
        },
        {
          "file": "lib/crawl/multiPage.js",
          "loc": 318,
          "exports": [
            "registrableDomain",
            "isSameSite",
            "normalizeCrawlUrl",
            "shouldSkipCrawlTarget",
            "parseRawLinks",
            "crawlLinkedPages",
            "mergeElements",
            "elementDedupeKey",
            "readLinksFromDom",
            "readPageSummaryFromDom"
          ]
        },
        {
          "file": "lib/crawl/pageStructure.js",
          "loc": 107,
          "exports": [
            "analyzePageStructure"
          ]
        },
        {
          "file": "lib/crawl/signals.js",
          "loc": 32,
          "exports": [
            "detectAntiBot",
            "detectDynamicContent"
          ]
        }
      ]
    },
    {
      "folder": "lib/flows",
      "role": "user-journey detection (light · pro)",
      "modules": [
        {
          "file": "lib/flows/lightFlows.js",
          "loc": 112,
          "exports": [
            "detectUserFlows"
          ]
        },
        {
          "file": "lib/flows/proFlows.js",
          "loc": 2,
          "exports": []
        }
      ]
    },
    {
      "folder": "lib/flows/pro",
      "role": "pro flow builders (common · form · type · helpers)",
      "modules": [
        {
          "file": "lib/flows/pro/commonFlows.js",
          "loc": 68,
          "exports": [
            "buildCommonFlows"
          ]
        },
        {
          "file": "lib/flows/pro/formFlows.js",
          "loc": 155,
          "exports": [
            "buildFormAndFallbackFlows",
            "buildContactFormFlow",
            "buildLoginFormFlow",
            "buildGenericSearchFlow",
            "buildGenericMediaFlow"
          ]
        },
        {
          "file": "lib/flows/pro/helpers.js",
          "loc": 56,
          "exports": [
            "MAX_ELEMENT_SELECTORS",
            "DEFAULT_ELEMENT_SELECTORS",
            "createElementContext",
            "hasFlowNamed",
            "formsWithPurpose",
            "createFlow"
          ]
        },
        {
          "file": "lib/flows/pro/index.js",
          "loc": 25,
          "exports": [
            "detectUserFlows"
          ]
        },
        {
          "file": "lib/flows/pro/typeFlows.js",
          "loc": 261,
          "exports": [
            "TYPE_FLOW_BUILDERS",
            "buildTypeSpecificFlows"
          ]
        }
      ]
    },
    {
      "folder": "lib/format",
      "role": "shape analysis for the BA agent",
      "modules": [
        {
          "file": "lib/format/baLight.js",
          "loc": 42,
          "exports": [
            "formatObservationsForBA"
          ]
        },
        {
          "file": "lib/format/baPro.js",
          "loc": 51,
          "exports": [
            "formatForBAAgent"
          ]
        }
      ]
    },
    {
      "folder": "lib/generate",
      "role": "BRD + suggested test cases (light · pro)",
      "modules": [
        {
          "file": "lib/generate/lightBrd.js",
          "loc": 221,
          "exports": [
            "generateBRD",
            "generateExecutiveSummary",
            "generateInScopeItems",
            "generateFunctionalRequirements",
            "generateRiskAssessment"
          ]
        },
        {
          "file": "lib/generate/lightFeatures.js",
          "loc": 133,
          "exports": [
            "detectFeatures",
            "generateAutomationSelectors"
          ]
        },
        {
          "file": "lib/generate/lightTestCases.js",
          "loc": 121,
          "exports": [
            "generateTestCasesFromAnalysis"
          ]
        },
        {
          "file": "lib/generate/majorFunctionalCases.js",
          "loc": 357,
          "exports": [
            "generateMajorFunctionalCases",
            "mergeMajorWithGenerated",
            "priorityRank",
            "WEBSITE_TYPES"
          ]
        },
        {
          "file": "lib/generate/proBrd.js",
          "loc": 454,
          "exports": [
            "generateBRD",
            "generateKeyFindings",
            "generateInScopeItems",
            "generateFunctionalRequirements",
            "generateRiskAssessment",
            "generateElementSummary"
          ]
        },
        {
          "file": "lib/generate/proTestCases.js",
          "loc": 525,
          "exports": [
            "generateTestCases",
            "generateBRDTestCases",
            "getExpectedBehavior",
            "getPostconditions",
            "getTestDataForField"
          ]
        }
      ]
    },
    {
      "folder": "lib/strategies",
      "role": "crawl orchestration (light · pro)",
      "modules": [
        {
          "file": "lib/strategies/light.js",
          "loc": 171,
          "exports": [
            "analyzeUrl"
          ]
        },
        {
          "file": "lib/strategies/pro.js",
          "loc": 298,
          "exports": [
            "analyzeUrlPro",
            "hasInsufficientEvidence"
          ]
        }
      ]
    }
  ],
  "tree": "packages/analyzer/\n├─ index.js\n├─ urlAnalyzer.js\n├─ urlAnalyzerPro.js\n├─ lib/\n│  ├─ classify/\n│  ├─ constants.js\n│  ├─ crawl/\n│  ├─ flows/\n│  ├─ format/\n│  ├─ generate/\n│  ├─ selectors.js\n│  ├─ strategies/"
};
