// AUTO-GENERATED by scripts/generate-lld.mjs — do not edit by hand.
// Run `npm run docs` (in support/zero-docs) to refresh from the live tree.

export interface GeneratedModule {
  id: string;
  kind: 'app' | 'web' | 'package';
  path: string;
  pkg: string;
  version: string | null;
  description: string;
  entry: string | null;
  scripts: string[];
  runtimeDeps: string[];
  workspaceDeps: string[];
  devDeps: string[];
  fileCount: number;
  loc: number;
  filesByExt: Record<string, number>;
  hasDockerfile: boolean;
  hasTests: boolean;
  tree: string;
}

export interface GeneratedLld {
  generatedAt: string;
  totals: { modules: number; fileCount: number; loc: number };
  modules: GeneratedModule[];
}

export const GENERATED_LLD: GeneratedLld = {
  "generatedAt": "2026-08-27T15:57:02.067Z",
  "totals": {
    "modules": 10,
    "fileCount": 211,
    "loc": 32573
  },
  "modules": [
    {
      "id": "api",
      "kind": "app",
      "path": "services/api",
      "pkg": "@zero/api",
      "version": "0.0.0",
      "description": "HTTP intake: auth, runs, SSE, presign. No Playwright. Routes in src/routes/.",
      "entry": "server.js",
      "scripts": [
        "dev",
        "start"
      ],
      "runtimeDeps": [
        "axios",
        "cloudinary",
        "compression",
        "cors",
        "dotenv",
        "express",
        "express-rate-limit",
        "express-validator",
        "helmet",
        "jsonwebtoken",
        "morgan",
        "multer",
        "node-cache",
        "pdfkit",
        "pg",
        "swagger-jsdoc",
        "swagger-ui-express",
        "uuid",
        "winston",
        "xlsx"
      ],
      "workspaceDeps": [
        "@zero/cloud",
        "@zero/db",
        "@zero/domain",
        "@zero/locators"
      ],
      "devDeps": [],
      "fileCount": 15,
      "loc": 3036,
      "filesByExt": {
        ".js": 15
      },
      "hasDockerfile": false,
      "hasTests": false,
      "tree": "services/api/\n├─ apiKeyManager.js\n├─ auth.js\n├─ encryption.js\n├─ logger.js\n├─ middleware.js\n├─ server.js\n├─ swagger.js\n├─ middleware/\n│  ├─ auth.js\n├─ src/\n│  ├─ routes/"
    },
    {
      "id": "orchestrator",
      "kind": "app",
      "path": "services/orchestrator",
      "pkg": "@zero/orchestrator",
      "version": "0.0.0",
      "description": "DAG worker: consumes runs.requested, walks stageKeys via processRun.js, calls LLM/templates.",
      "entry": "index.js",
      "scripts": [
        "start"
      ],
      "runtimeDeps": [
        "axios",
        "dotenv",
        "pg",
        "xlsx"
      ],
      "workspaceDeps": [
        "@zero/builders",
        "@zero/cloud",
        "@zero/db",
        "@zero/domain",
        "@zero/locators"
      ],
      "devDeps": [],
      "fileCount": 8,
      "loc": 2396,
      "filesByExt": {
        ".js": 8
      },
      "hasDockerfile": true,
      "hasTests": false,
      "tree": "services/orchestrator/\n├─ applyLlm.js\n├─ encryption.js\n├─ index.js\n├─ inferDomain.js\n├─ pipeline.js\n├─ processRun.js\n├─ worker.js\n├─ llm/\n│  ├─ index.js"
    },
    {
      "id": "executor",
      "kind": "app",
      "path": "services/executor",
      "pkg": "@zero/executor",
      "version": "0.0.0",
      "description": "Playwright job worker: consumes execution.requested. Owns Chromium.",
      "entry": "worker.js",
      "scripts": [
        "start"
      ],
      "runtimeDeps": [
        "dotenv",
        "pg",
        "playwright"
      ],
      "workspaceDeps": [
        "@zero/analyzer",
        "@zero/builders",
        "@zero/cloud",
        "@zero/db",
        "@zero/domain",
        "@zero/locators"
      ],
      "devDeps": [],
      "fileCount": 5,
      "loc": 2994,
      "filesByExt": {
        ".js": 5
      },
      "hasDockerfile": true,
      "hasTests": false,
      "tree": "services/executor/\n├─ browser.js\n├─ cmsCapture.js\n├─ jobs.js\n├─ main.js\n├─ worker.js"
    },
    {
      "id": "web",
      "kind": "web",
      "path": "web",
      "pkg": "@zero/web",
      "version": "0.0.0",
      "description": "",
      "entry": null,
      "scripts": [
        "build",
        "dev",
        "preview"
      ],
      "runtimeDeps": [
        "react",
        "react-dom"
      ],
      "workspaceDeps": [],
      "devDeps": [
        "@vitejs/plugin-react",
        "sass",
        "vite"
      ],
      "fileCount": 58,
      "loc": 13831,
      "filesByExt": {
        ".jsx": 23,
        ".scss": 26,
        ".js": 9
      },
      "hasDockerfile": true,
      "hasTests": false,
      "tree": "web/\n├─ vite.config.js\n├─ public/\n│  ├─ architecture.html\n│  ├─ architectureV2.html\n│  ├─ favicon.svg\n│  ├─ lld-web.html\n├─ src/\n│  ├─ App.jsx\n│  ├─ App.scss\n│  ├─ apiBase.js\n│  ├─ components/\n│  ├─ data/\n│  ├─ index.scss\n│  ├─ layouts/\n│  ├─ lib/"
    },
    {
      "id": "cloud",
      "kind": "package",
      "path": "packages/cloud",
      "pkg": "@zero/cloud",
      "version": "0.0.0",
      "description": "Provider-agnostic queue, object store, secrets, and cache adapters.",
      "entry": "index.js",
      "scripts": [],
      "runtimeDeps": [
        "express",
        "ioredis"
      ],
      "workspaceDeps": [
        "@zero/domain"
      ],
      "devDeps": [],
      "fileCount": 33,
      "loc": 1954,
      "filesByExt": {
        ".js": 32,
        ".ts": 1
      },
      "hasDockerfile": false,
      "hasTests": false,
      "tree": "packages/cloud/\n├─ http.js\n├─ index.d.ts\n├─ index.js\n├─ redisCache.js\n├─ redisQueue.js\n├─ aws/\n│  ├─ README.md\n│  ├─ cache.js\n│  ├─ index.js\n│  ├─ objectStore.js\n│  ├─ queue.js\n│  ├─ secrets.js\n├─ azure/\n│  ├─ README.md\n│  ├─ cache.js\n│  ├─ index.js\n│  ├─ objectStore.js\n│  ├─ queue.js\n│  ├─ secrets.js\n├─ conformance/\n│  ├─ gate9.js\n├─ gcp/\n│  ├─ README.md\n│  ├─ cache.js\n│  ├─ index.js\n│  ├─ objectStore.js\n│  ├─ queue.js\n│  ├─ secrets.js\n├─ lib/\n│  ├─ index.js\n│  ├─ provider.js\n├─ local/\n│  ├─ cache.js\n│  ├─ index.js\n│  ├─ queue.js\n│  ├─ secrets.js\n│  ├─ storage.js\n├─ vercel/\n│  ├─ README.md\n│  ├─ cache.js\n│  ├─ index.js\n│  ├─ objectStore.js\n│  ├─ queue.js\n│  ├─ secrets.js"
    },
    {
      "id": "domain",
      "kind": "package",
      "path": "packages/domain",
      "pkg": "@zero/domain",
      "version": "0.0.0",
      "description": "Shared contracts: stageKeys, appProfiles. No I/O.",
      "entry": "index.js",
      "scripts": [],
      "runtimeDeps": [],
      "workspaceDeps": [],
      "devDeps": [],
      "fileCount": 12,
      "loc": 599,
      "filesByExt": {
        ".js": 12
      },
      "hasDockerfile": false,
      "hasTests": false,
      "tree": "packages/domain/\n├─ execution.js\n├─ index.js\n├─ outputRoots.js\n├─ lib/\n│  ├─ execution.js\n│  ├─ executionModes.js\n│  ├─ index.js\n│  ├─ outputRoots.js\n│  ├─ profiles.js\n│  ├─ runCancel.js\n│  ├─ schemas.js\n│  ├─ stages.js"
    },
    {
      "id": "db",
      "kind": "package",
      "path": "packages/db",
      "pkg": "@zero/db",
      "version": "0.0.0",
      "description": "Postgres helpers and DDL for qa_runs, qa_assets, locators.",
      "entry": "index.js",
      "scripts": [],
      "runtimeDeps": [],
      "workspaceDeps": [
        "@zero/domain"
      ],
      "devDeps": [],
      "fileCount": 15,
      "loc": 851,
      "filesByExt": {
        ".js": 15
      },
      "hasDockerfile": false,
      "hasTests": false,
      "tree": "packages/db/\n├─ index.js\n├─ runStore.js\n├─ lib/\n│  ├─ assets.js\n│  ├─ config.js\n│  ├─ elements.js\n│  ├─ index.js\n│  ├─ projects.js\n│  ├─ providers.js\n│  ├─ runStore.js\n│  ├─ runs.js\n├─ migrations/\n│  ├─ 001_initial.sql"
    },
    {
      "id": "locators",
      "kind": "package",
      "path": "packages/locators",
      "pkg": "@zero/locators",
      "version": "0.0.0",
      "description": "Locator merge (profile → memory → DB) and element-key normalizer.",
      "entry": "index.js",
      "scripts": [],
      "runtimeDeps": [],
      "workspaceDeps": [
        "@zero/db"
      ],
      "devDeps": [],
      "fileCount": 15,
      "loc": 942,
      "filesByExt": {
        ".js": 15
      },
      "hasDockerfile": false,
      "hasTests": false,
      "tree": "packages/locators/\n├─ ecommerceSelectors.js\n├─ elementLogger.js\n├─ index.js\n├─ locatorRegistry.js\n├─ lib/\n│  ├─ ecommerce/\n│  ├─ elements/\n│  ├─ index.js\n│  ├─ merge/\n│  ├─ shared/"
    },
    {
      "id": "builders",
      "kind": "package",
      "path": "packages/builders",
      "pkg": "@zero/builders",
      "version": "0.0.0",
      "description": "Playwright spec and Java/Selenium emitters.",
      "entry": "index.js",
      "scripts": [],
      "runtimeDeps": [],
      "workspaceDeps": [
        "@zero/locators"
      ],
      "devDeps": [],
      "fileCount": 19,
      "loc": 895,
      "filesByExt": {
        ".js": 19
      },
      "hasDockerfile": false,
      "hasTests": false,
      "tree": "packages/builders/\n├─ index.js\n├─ javaSeleniumBuilder.js\n├─ scriptBuilder.js\n├─ lib/\n│  ├─ playwright/\n│  ├─ selenium/\n│  ├─ shared/"
    },
    {
      "id": "analyzer",
      "kind": "package",
      "path": "packages/analyzer",
      "pkg": "@zero/analyzer",
      "version": "0.0.0",
      "description": "Optional URL crawl that seeds BA when notes are short.",
      "entry": "index.js",
      "scripts": [],
      "runtimeDeps": [],
      "workspaceDeps": [
        "@zero/locators"
      ],
      "devDeps": [],
      "fileCount": 31,
      "loc": 5075,
      "filesByExt": {
        ".js": 31
      },
      "hasDockerfile": false,
      "hasTests": false,
      "tree": "packages/analyzer/\n├─ index.js\n├─ urlAnalyzer.js\n├─ urlAnalyzerPro.js\n├─ lib/\n│  ├─ classify/\n│  ├─ constants.js\n│  ├─ crawl/\n│  ├─ flows/\n│  ├─ format/\n│  ├─ generate/\n│  ├─ selectors.js\n│  ├─ strategies/"
    }
  ]
};

export type TaskTrack = 'capability' | 'packaging' | 'product' | 'ux';
export type TaskStatus = 'done' | 'partial' | 'not-done';

export interface GeneratedTask {
  id: string;
  name: string;
  track: TaskTrack;
  order: number;
  status: TaskStatus;
  spec: string;
  summary: string;
  dependsOn: string[];
  workspaces: string[];
}

export interface GeneratedWorkflow {
  generatedAt: string;
  northStar: string;
  currentTrack: string;
  current: string | null;
  acceptanceFloor: string | null;
  allComplete: boolean;
  tasks: GeneratedTask[];
  byWorkspace: Record<string, string[]>;
  latestNote: string;
}

export const GENERATED_WORKFLOW: GeneratedWorkflow = {
  "generatedAt": "2026-08-27T15:57:02.067Z",
  "northStar": "Autonomous any-URL QA (Q1–Q5) · operator UI/UX U1–U2 · packaging S0–S7 · capability M1–M7",
  "currentTrack": "product",
  "current": "Q5",
  "acceptanceFloor": "M4",
  "allComplete": false,
  "tasks": [
    {
      "id": "M1",
      "name": "Durable store",
      "track": "capability",
      "order": 0,
      "status": "done",
      "spec": "support/agent-workflow/milestones/M1-durable-store.md",
      "summary": "Restore real Postgres persistence. Kill durability dependence on in-memory Maps.",
      "dependsOn": [],
      "workspaces": [
        "api",
        "orchestrator",
        "db",
        "locators"
      ]
    },
    {
      "id": "M2",
      "name": "Object store + signed URLs",
      "track": "capability",
      "order": 1,
      "status": "done",
      "spec": "support/agent-workflow/milestones/M2-object-store.md",
      "summary": "Move large artifacts off API-local disk. Browser uploads via presigned PUT; downloads via presigned GET.",
      "dependsOn": [
        "M1"
      ],
      "workspaces": [
        "executor",
        "cloud",
        "db"
      ]
    },
    {
      "id": "M3",
      "name": "Queue + orchestrator",
      "track": "capability",
      "order": 2,
      "status": "done",
      "spec": "support/agent-workflow/milestones/M3-queue-orchestrator.md",
      "summary": "Extract `processRun` into a worker that consumes `runs.requested`. API returns immediately; progress via cache pub/sub → SSE.",
      "dependsOn": [
        "M1",
        "M2"
      ],
      "workspaces": [
        "orchestrator",
        "cloud"
      ]
    },
    {
      "id": "M4",
      "name": "Execution farm",
      "track": "capability",
      "order": 3,
      "status": "done",
      "spec": "support/agent-workflow/milestones/M4-execution-farm.md",
      "summary": "Playwright runs in isolated jobs behind `execution.requested`. Fan-out per TC batch; retries via queue; concurrency caps.",
      "dependsOn": [
        "M3"
      ],
      "workspaces": [
        "executor"
      ]
    },
    {
      "id": "M5",
      "name": "Auth + ACL",
      "track": "capability",
      "order": 4,
      "status": "done",
      "spec": "support/agent-workflow/milestones/M5-auth-acl.md",
      "summary": "Real identity and tenant scoping. No spoofable headers; no public artifacts; recording CORS not `*`.",
      "dependsOn": [
        "M1",
        "M4",
        "M2"
      ],
      "workspaces": []
    },
    {
      "id": "M6",
      "name": "LLM wiring",
      "track": "capability",
      "order": 5,
      "status": "done",
      "spec": "support/agent-workflow/milestones/M6-llm-wiring.md",
      "summary": "Provider keys + agent settings actually drive BA/Manager (and Manual/Automation as designed).",
      "dependsOn": [
        "M3",
        "M5"
      ],
      "workspaces": []
    },
    {
      "id": "M7",
      "name": "Multi-cloud adapters",
      "track": "capability",
      "order": 6,
      "status": "done",
      "spec": "support/agent-workflow/milestones/M7-multi-cloud.md",
      "summary": "`lib/cloud/*` implementations for AWS + one other cloud. IaC modules. CI smoke.",
      "dependsOn": [
        "M1",
        "M4",
        "M5",
        "M6"
      ],
      "workspaces": [
        "cloud"
      ]
    },
    {
      "id": "S0",
      "name": "Containerize the monolith",
      "track": "packaging",
      "order": 0,
      "status": "done",
      "spec": "support/agent-workflow/milestones/S0-containerize.md",
      "summary": "One `Dockerfile` + `docker-compose.yml` for the monolith, plus Postgres / Redis / MinIO. No code moves.",
      "dependsOn": [],
      "workspaces": []
    },
    {
      "id": "S1",
      "name": "Smoke tests",
      "track": "packaging",
      "order": 1,
      "status": "done",
      "spec": "support/agent-workflow/milestones/S1-smoke.md",
      "summary": "Jest boots the app, starts a run, and (when Postgres is up) asserts a `qa_runs` row. Without that, later splits are unverifiable.",
      "dependsOn": [
        "S0"
      ],
      "workspaces": [
        "db"
      ]
    },
    {
      "id": "S2",
      "name": "Turn on workspaces",
      "track": "packaging",
      "order": 2,
      "status": "done",
      "spec": "support/agent-workflow/milestones/S2-workspaces.md",
      "summary": "Root becomes workspaces-only. Shared code lives in `packages/*`, deployables in `services/*`, UI in `web/`. Imports use npm package names (`@zero/api`). Still one Node process.",
      "dependsOn": [
        "S1"
      ],
      "workspaces": [
        "api",
        "web",
        "cloud"
      ]
    },
    {
      "id": "S3",
      "name": "Split routes from stages",
      "track": "packaging",
      "order": 3,
      "status": "done",
      "spec": "support/agent-workflow/milestones/S3-split-routes.md",
      "summary": "Carve the HTTP API composition root so routes live in files and the DAG walk lives in the Orchestrator worker. Same container, two clear halves — last step that is a pure refactor. Chromium may still launch in-process until S4.",
      "dependsOn": [
        "S2",
        "M1",
        "M7"
      ],
      "workspaces": [
        "api",
        "orchestrator",
        "executor",
        "domain"
      ]
    },
    {
      "id": "S4",
      "name": "Extract executor image",
      "track": "packaging",
      "order": 4,
      "status": "done",
      "spec": "support/agent-workflow/milestones/S4-executor-image.md",
      "summary": "Playwright leaves the HTTP API image. Chromium runs only in the Playwright executor container on `execution.requested`.",
      "dependsOn": [
        "S3"
      ],
      "workspaces": [
        "api",
        "executor"
      ]
    },
    {
      "id": "S5",
      "name": "Extract orchestrator image",
      "track": "packaging",
      "order": 5,
      "status": "done",
      "spec": "support/agent-workflow/milestones/S5-orchestrator-image.md",
      "summary": "Orchestrator worker is its own long-lived process. HTTP API returns immediately after publishing `runs.requested` and relays SSE from cache/Redis.",
      "dependsOn": [
        "S4"
      ],
      "workspaces": [
        "api",
        "orchestrator",
        "domain"
      ]
    },
    {
      "id": "S6",
      "name": "Cloud adapters remaining providers",
      "track": "packaging",
      "order": 6,
      "status": "done",
      "spec": "support/agent-workflow/milestones/S6-cloud-providers.md",
      "summary": "`@zero/cloud` already has `local` + `aws` + `gcp`. Finish the adapter set: Azure, Vercel-hybrid, and GATE-9 conformance tests that run against every provider.",
      "dependsOn": [
        "S2",
        "S4",
        "S5",
        "S3"
      ],
      "workspaces": [
        "cloud"
      ]
    },
    {
      "id": "S7",
      "name": "Web image split + /api prefix drop",
      "track": "packaging",
      "order": 7,
      "status": "done",
      "spec": "support/agent-workflow/milestones/S7-web-image.md",
      "summary": "Give `@zero/web` its own workspace-scoped image and its own origin. Drop the `/api` path prefix from every HTTP route so the API service owns route paths natively — no longer a folder-inside-a-monolith artifact.",
      "dependsOn": [
        "S5",
        "S6"
      ],
      "workspaces": [
        "api",
        "web",
        "cloud"
      ]
    },
    {
      "id": "Q1",
      "name": "Deep crawl (multi-page site understanding)",
      "track": "product",
      "order": 0,
      "status": "done",
      "spec": "support/agent-workflow/milestones/Q1-deep-crawl.md",
      "summary": "Expand the Web Analyzer so a URL-only run understands more than the landing page: follow primary navigation, crawl a bounded set of internal pages, and emit a structured site map for downstream test generation.",
      "dependsOn": [
        "M4"
      ],
      "workspaces": [
        "executor",
        "domain",
        "analyzer"
      ]
    },
    {
      "id": "Q2",
      "name": "Domain-driven major functional test cases",
      "track": "product",
      "order": 1,
      "status": "done",
      "spec": "support/agent-workflow/milestones/Q2-domain-test-generation.md",
      "summary": "Turn crawl + domain type into **major functional test cases** automatically when the user provides URL only (no CSV, no manual rows). Rules and templates first — not LLM.",
      "dependsOn": [
        "Q1"
      ],
      "workspaces": [
        "orchestrator",
        "web",
        "analyzer"
      ]
    },
    {
      "id": "Q3",
      "name": "Execute discovered flows",
      "track": "product",
      "order": 2,
      "status": "done",
      "spec": "support/agent-workflow/milestones/Q3-flow-execution.md",
      "summary": "Wire analyzer-generated flows into Playwright execution so URL-only runs **run** major functional checks, not just load the homepage and wait.",
      "dependsOn": [
        "Q2",
        "M4"
      ],
      "workspaces": [
        "executor",
        "domain",
        "locators",
        "builders"
      ]
    },
    {
      "id": "Q4",
      "name": "AI domain inference gate",
      "track": "product",
      "order": 3,
      "status": "done",
      "spec": "support/agent-workflow/milestones/Q4-ai-domain-inference.md",
      "summary": "When rule-based domain detection is uncertain, call the LLM **once** with a structured crawl snapshot to infer site purpose and major functional test areas. Templates remain the fallback when no key or LLM fails.",
      "dependsOn": [
        "Q1",
        "Q2",
        "M6"
      ],
      "workspaces": [
        "orchestrator",
        "web"
      ]
    },
    {
      "id": "Q5",
      "name": "Trustworthy site understanding and test-plan quality",
      "track": "product",
      "order": 4,
      "status": "not-done",
      "spec": "support/agent-workflow/milestones/Q5-domain-subdomain.md",
      "summary": "Q5 is a **recovery milestone**. The first implementation added a large sub-domain",
      "dependsOn": [
        "Q1",
        "Q2",
        "Q3",
        "Q4",
        "M6"
      ],
      "workspaces": []
    },
    {
      "id": "U1",
      "name": "Professional operator UI/UX",
      "track": "ux",
      "order": 0,
      "status": "done",
      "spec": "support/agent-workflow/milestones/U1-professional-ui-ux.md",
      "summary": "U1 is a **quality milestone for the SPA**. Tokens, a light/dark theme, and a FOWT-safe",
      "dependsOn": [
        "S7"
      ],
      "workspaces": [
        "web"
      ]
    },
    {
      "id": "U2",
      "name": "Ultra-low-friction canvas",
      "track": "ux",
      "order": 1,
      "status": "done",
      "spec": "support/agent-workflow/milestones/U2-low-friction-canvas.md",
      "summary": "U2 is a **presentation milestone**. The operator’s primary job is: paste a URL, start a",
      "dependsOn": [
        "U1",
        "Q5"
      ],
      "workspaces": [
        "web",
        "domain"
      ]
    }
  ],
  "byWorkspace": {
    "api": [
      "M1",
      "S2",
      "S3",
      "S4",
      "S5",
      "S7"
    ],
    "orchestrator": [
      "M1",
      "M3",
      "S3",
      "S5",
      "Q2",
      "Q4"
    ],
    "executor": [
      "M2",
      "M4",
      "S3",
      "S4",
      "Q1",
      "Q3"
    ],
    "web": [
      "S2",
      "S7",
      "Q2",
      "Q4",
      "U1",
      "U2"
    ],
    "cloud": [
      "M2",
      "M3",
      "M7",
      "S2",
      "S6",
      "S7"
    ],
    "domain": [
      "S3",
      "S5",
      "Q1",
      "Q3",
      "U2"
    ],
    "db": [
      "M1",
      "M2",
      "S1"
    ],
    "locators": [
      "M1",
      "Q3"
    ],
    "builders": [
      "Q3"
    ],
    "analyzer": [
      "Q1",
      "Q2"
    ]
  },
  "latestNote": "milestone_done: U1 operator shell (skip link, aria-current, type/space tokens, theme names) and U2 low-friction canvas (nrv--canvas, disclose, hover rail, always-on Run). Product current remains Q5."
};
