// AUTO-GENERATED by scripts/generate-packages-doc.mjs — do not edit by hand.
// Run `npm run packages-doc` to refresh from the live packages/* tree.

export interface PackageEntry {
  file: string;
  role: string;
  loc: number;
  reExportsFrom: string | null;
  exports: string[];
}

export interface PackageModule {
  file: string;
  loc: number;
  exports: string[];
}

export interface PackageFolder {
  folder: string;
  role: string;
  modules: PackageModule[];
}

export interface PackageDoc {
  id: string;
  generatedAt: string;
  pkg: string;
  version: string | null;
  description: string;
  main: string | null;
  exports: Record<string, string> | null;
  fileCount: number;
  loc: number;
  dependencies: string[];
  workspaceDeps: string[];
  entries: PackageEntry[];
  modules: PackageFolder[];
  tree: string;
  tests: string[];
}

export const PACKAGES_DOC: PackageDoc[] = [
  {
    "id": "domain",
    "generatedAt": "2026-08-18T04:07:58.105Z",
    "pkg": "@zero/domain",
    "version": "0.0.0",
    "description": "Shared contracts: stageKeys, appProfiles. No I/O.",
    "main": "index.js",
    "exports": {
      ".": "./index.js",
      "./execution": "./execution.js",
      "./outputRoots": "./outputRoots.js",
      "./schemas": "./lib/schemas.js"
    },
    "fileCount": 10,
    "loc": 441,
    "dependencies": [],
    "workspaceDeps": [],
    "entries": [
      {
        "file": "index.js",
        "role": "unified export (stages · profiles · outputRoots)",
        "loc": 2,
        "reExportsFrom": "./lib",
        "exports": []
      },
      {
        "file": "execution.js",
        "role": "subpath — execution.requested protocol",
        "loc": 2,
        "reExportsFrom": "./lib/execution",
        "exports": []
      },
      {
        "file": "outputRoots.js",
        "role": "subpath — dist/ output roots",
        "loc": 2,
        "reExportsFrom": "./lib/outputRoots",
        "exports": []
      }
    ],
    "modules": [
      {
        "folder": "lib",
        "role": "package index + shared kernel",
        "modules": [
          {
            "file": "lib/execution.js",
            "loc": 51,
            "exports": []
          },
          {
            "file": "lib/executionModes.js",
            "loc": 40,
            "exports": [
              "EXECUTION_MODES",
              "resolveExecutionMode"
            ]
          },
          {
            "file": "lib/index.js",
            "loc": 19,
            "exports": [
              "stageKeys",
              "optionalStageKeys",
              "appProfiles",
              "RUNS_REQUESTED",
              "outputRoots",
              "validateRunInput",
              "EXECUTION_MODES",
              "resolveExecutionMode"
            ]
          },
          {
            "file": "lib/outputRoots.js",
            "loc": 49,
            "exports": [
              "distRoot",
              "webDir",
              "artifactsDir",
              "logsDir",
              "coverageDir",
              "localStoreDir"
            ]
          },
          {
            "file": "lib/profiles.js",
            "loc": 218,
            "exports": [
              "appProfiles"
            ]
          },
          {
            "file": "lib/schemas.js",
            "loc": 34,
            "exports": [
              "validateRunInput"
            ]
          },
          {
            "file": "lib/stages.js",
            "loc": 24,
            "exports": [
              "stageKeys",
              "optionalStageKeys",
              "RUNS_REQUESTED"
            ]
          }
        ]
      }
    ],
    "tree": "packages/domain/\n├─ execution.js\n├─ index.js\n├─ outputRoots.js\n├─ lib/\n│  ├─ execution.js\n│  ├─ executionModes.js\n│  ├─ index.js\n│  ├─ outputRoots.js\n│  ├─ profiles.js\n│  ├─ schemas.js\n│  ├─ stages.js",
    "tests": [
      "test/domain.test.js"
    ]
  },
  {
    "id": "db",
    "generatedAt": "2026-08-18T04:07:58.112Z",
    "pkg": "@zero/db",
    "version": "0.0.0",
    "description": "Postgres helpers and DDL for qa_runs, qa_assets, locators.",
    "main": "index.js",
    "exports": {
      ".": "./index.js",
      "./runStore": "./runStore.js",
      "./schema": "./lib/schema/index.js"
    },
    "fileCount": 15,
    "loc": 849,
    "dependencies": [
      "@zero/domain"
    ],
    "workspaceDeps": [
      "@zero/domain"
    ],
    "entries": [
      {
        "file": "index.js",
        "role": "Postgres helpers + DDL init",
        "loc": 2,
        "reExportsFrom": "./lib",
        "exports": []
      },
      {
        "file": "runStore.js",
        "role": "subpath — file + DB + object-store run persistence",
        "loc": 2,
        "reExportsFrom": "./lib/runStore",
        "exports": []
      }
    ],
    "modules": [
      {
        "folder": "lib",
        "role": "public API barrel",
        "modules": [
          {
            "file": "lib/assets.js",
            "loc": 46,
            "exports": [
              "replaceAssets",
              "listAssetsByRunId"
            ]
          },
          {
            "file": "lib/config.js",
            "loc": 6,
            "exports": [
              "isDatabaseConfigured"
            ]
          },
          {
            "file": "lib/elements.js",
            "loc": 74,
            "exports": [
              "upsertLocator",
              "getLocatorsByHost",
              "insertElementLog",
              "getElementLogsByHost"
            ]
          },
          {
            "file": "lib/index.js",
            "loc": 62,
            "exports": [
              "isDatabaseConfigured",
              "sanitizeRunInput",
              "initAllTables",
              "initRunsTables",
              "initElementTables",
              "initProjectsTables",
              "initProviderTables",
              "runPendingMigrations",
              "upsertRun",
              "getRunById",
              "listRunRows",
              "replaceAssets",
              "listAssetsByRunId",
              "upsertLocator",
              "getLocatorsByHost",
              "insertElementLog",
              "getElementLogsByHost",
              "createProject",
              "listProjects",
              "getProject",
              "insertStoredScript",
              "getStoredScriptsByProject",
              "insertRecording",
              "listProviderKeys",
              "upsertProviderKey",
              "deleteProviderKey",
              "getEncryptedProviderKey",
              "listAgentSettings",
              "upsertAgentSettings"
            ]
          },
          {
            "file": "lib/projects.js",
            "loc": 51,
            "exports": [
              "createProject",
              "listProjects",
              "getProject",
              "insertStoredScript",
              "getStoredScriptsByProject",
              "insertRecording"
            ]
          },
          {
            "file": "lib/providers.js",
            "loc": 68,
            "exports": [
              "listProviderKeys",
              "upsertProviderKey",
              "deleteProviderKey",
              "getEncryptedProviderKey",
              "listAgentSettings",
              "upsertAgentSettings"
            ]
          },
          {
            "file": "lib/runs.js",
            "loc": 75,
            "exports": [
              "upsertRun",
              "getRunById",
              "listRunRows"
            ]
          },
          {
            "file": "lib/runStore.js",
            "loc": 186,
            "exports": [
              "createRunStore",
              "defaultArtifactsRoot",
              "rowToRun",
              "mergeOptionalArtifactsFromFile",
              "OPTIONAL_ARTIFACT_KEYS"
            ]
          },
          {
            "file": "lib/sanitize.js",
            "loc": 15,
            "exports": [
              "sanitizeRunInput"
            ]
          }
        ]
      },
      {
        "folder": "lib/schema",
        "role": "DDL table constants + initAllTables",
        "modules": [
          {
            "file": "lib/schema/index.js",
            "loc": 12,
            "exports": []
          },
          {
            "file": "lib/schema/init.js",
            "loc": 61,
            "exports": [
              "initAllTables",
              "initRunsTables",
              "initElementTables",
              "initProjectsTables",
              "initProviderTables"
            ]
          },
          {
            "file": "lib/schema/migrate.js",
            "loc": 61,
            "exports": [
              "listMigrationFiles",
              "runPendingMigrations"
            ]
          },
          {
            "file": "lib/schema/tables.js",
            "loc": 128,
            "exports": [
              "TABLE_QA_RUNS",
              "TABLE_QA_ASSETS",
              "TABLE_PROJECTS",
              "TABLE_STORED_SCRIPTS",
              "TABLE_RECORDINGS",
              "TABLE_ELEMENT_LOCATORS",
              "TABLE_ELEMENT_LOGS",
              "TABLE_PROVIDER_KEYS",
              "TABLE_AGENT_SETTINGS"
            ]
          }
        ]
      }
    ],
    "tree": "packages/db/\n├─ index.js\n├─ runStore.js\n├─ lib/\n│  ├─ assets.js\n│  ├─ config.js\n│  ├─ elements.js\n│  ├─ index.js\n│  ├─ projects.js\n│  ├─ providers.js\n│  ├─ runStore.js\n│  ├─ runs.js\n│  ├─ sanitize.js\n│  ├─ schema/index.js\n│  ├─ schema/init.js\n│  ├─ schema/migrate.js\n├─ migrations/",
    "tests": [
      "test/db.config.test.js",
      "test/db.persist.test.js"
    ]
  },
  {
    "id": "locators",
    "generatedAt": "2026-08-18T04:07:58.114Z",
    "pkg": "@zero/locators",
    "version": "0.0.0",
    "description": "Locator merge (profile → memory → DB) and element-key normalizer.",
    "main": "index.js",
    "exports": {
      ".": "./index.js",
      "./locatorRegistry": "./locatorRegistry.js",
      "./elementLogger": "./elementLogger.js",
      "./ecommerceSelectors": "./ecommerceSelectors.js"
    },
    "fileCount": 15,
    "loc": 942,
    "dependencies": [
      "@zero/db"
    ],
    "workspaceDeps": [
      "@zero/db"
    ],
    "entries": [
      {
        "file": "index.js",
        "role": "unified export (merge · elements · ecommerce)",
        "loc": 2,
        "reExportsFrom": "./lib",
        "exports": []
      },
      {
        "file": "locatorRegistry.js",
        "role": "subpath — profile → memory → DB merge",
        "loc": 2,
        "reExportsFrom": "./lib/merge",
        "exports": []
      },
      {
        "file": "elementLogger.js",
        "role": "subpath — element-key normalizer + DB upsert",
        "loc": 2,
        "reExportsFrom": "./lib/elements",
        "exports": []
      },
      {
        "file": "ecommerceSelectors.js",
        "role": "subpath — domain-aware e-commerce selectors",
        "loc": 2,
        "reExportsFrom": "./lib/ecommerce",
        "exports": []
      }
    ],
    "modules": [
      {
        "folder": "lib",
        "role": "",
        "modules": [
          {
            "file": "lib/index.js",
            "loc": 10,
            "exports": []
          }
        ]
      },
      {
        "folder": "lib/ecommerce",
        "role": "domainSelectors data + detectDomain runtime",
        "modules": [
          {
            "file": "lib/ecommerce/index.js",
            "loc": 2,
            "exports": []
          },
          {
            "file": "lib/ecommerce/runtime.js",
            "loc": 52,
            "exports": [
              "domainSelectors",
              "detectDomain",
              "getSelectors",
              "getDomainConfig"
            ]
          },
          {
            "file": "lib/ecommerce/selectors.js",
            "loc": 643,
            "exports": [
              "domainSelectors"
            ]
          }
        ]
      },
      {
        "folder": "lib/elements",
        "role": "normalizeElementKey · parseElementEntry · processElementLog",
        "modules": [
          {
            "file": "lib/elements/index.js",
            "loc": 13,
            "exports": [
              "hostFromUrl",
              "normalizeElementKey",
              "parseElementEntry",
              "processElementLog",
              "ELEMENT_KEYS"
            ]
          },
          {
            "file": "lib/elements/keys.js",
            "loc": 53,
            "exports": [
              "ELEMENT_KEYS",
              "KEY_ALIASES",
              "normalizeElementKey"
            ]
          },
          {
            "file": "lib/elements/logger.js",
            "loc": 43,
            "exports": [
              "processElementLog"
            ]
          },
          {
            "file": "lib/elements/parser.js",
            "loc": 22,
            "exports": [
              "parseElementEntry"
            ]
          }
        ]
      },
      {
        "folder": "lib/merge",
        "role": "mergeSelectorCandidates · getMergedSelectors",
        "modules": [
          {
            "file": "lib/merge/index.js",
            "loc": 16,
            "exports": [
              "hostFromUrl",
              "mergeSelectorCandidates",
              "getMergedSelectors",
              "dbLocatorsToCandidates",
              "hydrateSelectorMemory"
            ]
          },
          {
            "file": "lib/merge/registry.js",
            "loc": 70,
            "exports": [
              "mergeSelectorCandidates",
              "getMergedSelectors",
              "dbLocatorsToCandidates",
              "hydrateSelectorMemory"
            ]
          }
        ]
      },
      {
        "folder": "lib/shared",
        "role": "hostFromUrl and shared helpers",
        "modules": [
          {
            "file": "lib/shared/url.js",
            "loc": 10,
            "exports": [
              "hostFromUrl"
            ]
          }
        ]
      }
    ],
    "tree": "packages/locators/\n├─ ecommerceSelectors.js\n├─ elementLogger.js\n├─ index.js\n├─ locatorRegistry.js\n├─ lib/\n│  ├─ ecommerce/index.js\n│  ├─ ecommerce/runtime.js\n│  ├─ ecommerce/selectors.js\n│  ├─ elements/index.js\n│  ├─ elements/keys.js\n│  ├─ elements/logger.js\n│  ├─ elements/parser.js\n│  ├─ index.js\n│  ├─ merge/index.js\n│  ├─ merge/registry.js\n│  ├─ shared/url.js",
    "tests": [
      "test/locators.test.js"
    ]
  },
  {
    "id": "builders",
    "generatedAt": "2026-08-18T04:07:58.115Z",
    "pkg": "@zero/builders",
    "version": "0.0.0",
    "description": "Playwright spec and Java/Selenium emitters.",
    "main": "index.js",
    "exports": {
      ".": "./index.js",
      "./scriptBuilder": "./scriptBuilder.js",
      "./javaSeleniumBuilder": "./javaSeleniumBuilder.js",
      "./playwright": "./lib/playwright/index.js",
      "./playwright/discoveredFlows": "./lib/playwright/discoveredFlows.js",
      "./selenium": "./lib/selenium/index.js",
      "./shared/selectors": "./lib/shared/selectors.js",
      "./shared/text": "./lib/shared/text.js"
    },
    "fileCount": 19,
    "loc": 895,
    "dependencies": [
      "@zero/locators"
    ],
    "workspaceDeps": [
      "@zero/locators"
    ],
    "entries": [
      {
        "file": "index.js",
        "role": "unified export (Playwright + Selenium)",
        "loc": 5,
        "reExportsFrom": "lib/* (spread)",
        "exports": []
      },
      {
        "file": "scriptBuilder.js",
        "role": "subpath — Playwright spec emitters",
        "loc": 2,
        "reExportsFrom": "./lib/playwright",
        "exports": []
      },
      {
        "file": "javaSeleniumBuilder.js",
        "role": "subpath — Java/Selenium class emitters",
        "loc": 2,
        "reExportsFrom": "./lib/selenium",
        "exports": []
      }
    ],
    "modules": [
      {
        "folder": "lib/playwright",
        "role": "channel · test-case · ecommerce Playwright specs",
        "modules": [
          {
            "file": "lib/playwright/channelSpec.js",
            "loc": 39,
            "exports": [
              "buildPlaywrightSpec",
              "buildChannelFlowSteps"
            ]
          },
          {
            "file": "lib/playwright/discoveredFlows.js",
            "loc": 214,
            "exports": [
              "MAX_FLOWS",
              "pickCriticalFlows",
              "normalizeFlowSteps",
              "executeFlowStep",
              "buildDiscoveredFlowTests",
              "runDiscoveredFlows"
            ]
          },
          {
            "file": "lib/playwright/ecommerceSpec.js",
            "loc": 159,
            "exports": [
              "buildEcommerceSpec",
              "buildEcommerceTestBody"
            ]
          },
          {
            "file": "lib/playwright/executionSteps.js",
            "loc": 6,
            "exports": [
              "buildExecutionSteps"
            ]
          },
          {
            "file": "lib/playwright/helpers.js",
            "loc": 37,
            "exports": [
              "PLAYWRIGHT_IMPORT",
              "PLAYWRIGHT_HELPER_FUNCTIONS",
              "buildPlaywrightHeader"
            ]
          },
          {
            "file": "lib/playwright/index.js",
            "loc": 18,
            "exports": [
              "buildPlaywrightSpec",
              "buildPlaywrightSpecFromTestCases",
              "buildEcommerceSpec",
              "buildExecutionSteps",
              "buildDiscoveredFlowTests",
              "runDiscoveredFlows"
            ]
          },
          {
            "file": "lib/playwright/testCasesSpec.js",
            "loc": 36,
            "exports": [
              "buildPlaywrightSpecFromTestCases",
              "normalizeTestCases"
            ]
          }
        ]
      },
      {
        "folder": "lib/selenium",
        "role": "Java test · class · ecommerce Selenium emitters",
        "modules": [
          {
            "file": "lib/selenium/ecommerceSelenium.js",
            "loc": 128,
            "exports": [
              "buildEcommerceSelenium"
            ]
          },
          {
            "file": "lib/selenium/index.js",
            "loc": 12,
            "exports": [
              "buildSeleniumJavaTest",
              "buildSeleniumJavaClass",
              "buildEcommerceSelenium",
              "escapeJava"
            ]
          },
          {
            "file": "lib/selenium/javaClass.js",
            "loc": 39,
            "exports": [
              "buildSeleniumJavaClass"
            ]
          },
          {
            "file": "lib/selenium/javaTest.js",
            "loc": 61,
            "exports": [
              "buildSeleniumJavaTest"
            ]
          },
          {
            "file": "lib/selenium/locatorBy.js",
            "loc": 10,
            "exports": [
              "toSeleniumBy"
            ]
          },
          {
            "file": "lib/selenium/selectorConstants.js",
            "loc": 31,
            "exports": [
              "generateSelectorConstants"
            ]
          }
        ]
      },
      {
        "folder": "lib/shared",
        "role": "text helpers · OTT selectors · ecommerce config",
        "modules": [
          {
            "file": "lib/shared/ecommerce.js",
            "loc": 14,
            "exports": [
              "loadEcommerceConfig"
            ]
          },
          {
            "file": "lib/shared/selectors.js",
            "loc": 54,
            "exports": [
              "DEFAULT_OTT_SELECTORS",
              "pickSelectors",
              "resolveOttSelectors",
              "flattenLocatorValues"
            ]
          },
          {
            "file": "lib/shared/text.js",
            "loc": 28,
            "exports": [
              "escapeJava",
              "sanitizeTestTitle",
              "toJavaClassName",
              "toJavaMethodName"
            ]
          }
        ]
      }
    ],
    "tree": "packages/builders/\n├─ index.js\n├─ javaSeleniumBuilder.js\n├─ scriptBuilder.js\n├─ lib/\n│  ├─ playwright/channelSpec.js\n│  ├─ playwright/discoveredFlows.js\n│  ├─ playwright/ecommerceSpec.js\n│  ├─ playwright/executionSteps.js\n│  ├─ playwright/helpers.js\n│  ├─ playwright/index.js\n│  ├─ playwright/testCasesSpec.js\n│  ├─ selenium/ecommerceSelenium.js\n│  ├─ selenium/index.js\n│  ├─ selenium/javaClass.js\n│  ├─ selenium/javaTest.js\n│  ├─ selenium/locatorBy.js",
    "tests": [
      "test/builders.test.js"
    ]
  },
  {
    "id": "cloud",
    "generatedAt": "2026-08-18T04:07:58.116Z",
    "pkg": "@zero/cloud",
    "version": "0.0.0",
    "description": "Provider-agnostic queue, object store, secrets, and cache adapters.",
    "main": "index.js",
    "exports": {
      ".": "./index.js",
      "./http": "./http.js"
    },
    "fileCount": 32,
    "loc": 1915,
    "dependencies": [
      "@zero/domain",
      "express",
      "ioredis"
    ],
    "workspaceDeps": [
      "@zero/domain"
    ],
    "entries": [
      {
        "file": "index.js",
        "role": "ZERO_CLOUD bindings (objectStore · queue · secrets · cache)",
        "loc": 6,
        "reExportsFrom": null,
        "exports": []
      },
      {
        "file": "http.js",
        "role": "subpath — local signed URL HTTP handler",
        "loc": 86,
        "reExportsFrom": null,
        "exports": [
          "createCloudRouter",
          "objectKey",
          "readObjectBuffer"
        ]
      }
    ],
    "modules": [
      {
        "folder": "lib",
        "role": "createCloudBindings · provider loader",
        "modules": [
          {
            "file": "lib/index.js",
            "loc": 25,
            "exports": [
              "createCloudBindings",
              "loadProvider",
              "normalizeProviderName"
            ]
          },
          {
            "file": "lib/provider.js",
            "loc": 22,
            "exports": [
              "SUPPORTED_PROVIDERS",
              "normalizeProviderName",
              "loadProvider"
            ]
          }
        ]
      }
    ],
    "tree": "packages/cloud/\n├─ http.js\n├─ index.js\n├─ redisCache.js\n├─ redisQueue.js\n├─ aws/\n│  ├─ cache.js\n│  ├─ index.js\n│  ├─ objectStore.js\n│  ├─ queue.js\n│  ├─ secrets.js\n├─ azure/\n│  ├─ cache.js\n│  ├─ index.js\n│  ├─ objectStore.js\n│  ├─ queue.js\n│  ├─ secrets.js\n├─ conformance/\n│  ├─ gate9.js\n├─ gcp/\n│  ├─ cache.js\n│  ├─ index.js\n│  ├─ objectStore.js\n│  ├─ queue.js\n│  ├─ secrets.js\n├─ lib/\n│  ├─ index.js\n│  ├─ provider.js\n├─ local/\n│  ├─ cache.js\n│  ├─ index.js\n│  ├─ queue.js\n│  ├─ secrets.js\n│  ├─ storage.js\n├─ vercel/\n│  ├─ cache.js\n│  ├─ index.js\n│  ├─ objectStore.js\n│  ├─ queue.js\n│  ├─ secrets.js",
    "tests": [
      "test/cloud.provider.test.js",
      "test/cloud.conformance.test.js",
      "test/cloud.store.test.js"
    ]
  }
];
export const PACKAGES_DOC_GENERATED_AT = "2026-08-18T04:07:58.117Z";
