const { escapeJava, toJavaClassName } = require("../shared/text");

/**
 * Build a full Java test class shell for a project.
 */
function buildSeleniumJavaClass(projectName, testCases, locatorsByKey, baseUrl) {
  const className = `${toJavaClassName(projectName, "OTT")}Test`;

  return [
    "import org.openqa.selenium.By;",
    "import org.openqa.selenium.WebDriver;",
    "import org.openqa.selenium.WebElement;",
    "import org.openqa.selenium.chrome.ChromeDriver;",
    "import org.openqa.selenium.support.ui.ExpectedConditions;",
    "import org.openqa.selenium.support.ui.WebDriverWait;",
    "import java.time.Duration;",
    "",
    "/** Generated by ZER0 - Automation language: Java (Selenium) */",
    `public class ${className} {`,
    "",
    `    private static final String BASE_URL = "${escapeJava(baseUrl || "")}";`,
    "",
    "    public static void main(String[] args) {",
    "        WebDriver driver = new ChromeDriver();",
    "        try {",
    "            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(15));",
    "            driver.get(BASE_URL);",
    '            wait.until(ExpectedConditions.visibilityOfElementLocated(By.tagName("body")));',
    "            // Add test method calls per TC",
    "        } finally {",
    "            driver.quit();",
    "        }",
    "    }",
    "}"
  ].join("\n");
}

module.exports = { buildSeleniumJavaClass };
